services:
    api:
        build: .
        volumes:
            - ../../../../../:/var/www/html
        ports:
            - "5200:5200"
        entrypoint: php bin/laravels start -i
        environment:
            LARAVELS_LISTEN_IP: "0.0.0.0"
            LARAVELS_HANDLE_STATIC: true
